platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.6.1-jdk-8

inputs:
  - name: git
  - name: version

outputs:
  - name: package
  - name: qualitycheck-input
  - name: test-reports

caches:
  - path: maven

run:
  path: bash
  args:
    - -exc
    - |
      export ROOT_FOLDER=$(pwd)
      ln -s "${ROOT_FOLDER}/maven" "${HOME}/.m2"
      cd git/backend
      cat ../../version/version
      mvn versions:set -DnewVersion=$(cat ../../version/version) -f pom.xml
      mvn verify -Djacoco.skip.check=true

      cp ./Dockerfile ../../package
      cp ./target/*-with-dependencies.jar ../../package

      cp ./pom.xml ../../qualitycheck-input
      cp -r ./src ../../qualitycheck-input
      cp -r ./target ../../qualitycheck-input

     # cp -r ./target/failsafe-reports/*.xml ../../test-reports
      # cp hiptest-publisher.conf ../../test-reports
